# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: challenge.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63hallenge.proto\x12\x0e\x61uthentication\"]\n\x10\x43hallengeRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x15\n\rchallengetype\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x11\n\tsignature\x18\x04 \x01(\t\"\x91\x01\n\x11\x43hallengeResponse\x12+\n\x07numbers\x18\x01 \x03(\x0b\x32\x1a.authentication.NumberData\x12\x13\n\x0btotal_pages\x18\x02 \x01(\x05\x12\x14\n\x0c\x63urrent_page\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x11\n\tsignature\x18\x05 \x01(\t\"\'\n\nNumberData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'challenge_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHALLENGEREQUEST._serialized_start=35
  _CHALLENGEREQUEST._serialized_end=128
  _CHALLENGERESPONSE._serialized_start=131
  _CHALLENGERESPONSE._serialized_end=276
  _NUMBERDATA._serialized_start=278
  _NUMBERDATA._serialized_end=317
# @@protoc_insertion_point(module_scope)
